'use client';

import { useState, useCallback } from 'react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import {
  FileText,
  Download,
  Copy,
  Check,
  ExternalLink,
  ChevronDown,
  ChevronUp,
} from 'lucide-react';

interface DocumentCardProps {
  title: string;
  description?: string;
  content: string;
  documentType?: string;
  wordCount?: number;
  generatedAt?: string;
}

// Opens the document in a styled print window — the browser's "Save as PDF"
// produces searchable, high-quality text (unlike html2canvas which makes images).
function printAsPDF(title: string, content: string) {
  const printWindow = window.open('', '_blank');
  if (!printWindow) return;

  // Build the HTML — inline all styles so no external resources needed
  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${escapeHTML(title)}</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }

    body {
      font-family: 'Georgia', 'Times New Roman', serif;
      font-size: 12pt;
      line-height: 1.7;
      color: #1a1a1a;
      background: #fff;
      padding: 2cm 2.5cm;
      max-width: 21cm;
      margin: 0 auto;
    }

    /* Title block */
    .doc-title {
      font-size: 22pt;
      font-weight: 700;
      margin-bottom: 0.3cm;
      color: #0a0a0a;
      border-bottom: 2px solid #0a0a0a;
      padding-bottom: 0.3cm;
    }
    .doc-meta {
      font-family: 'Helvetica Neue', Arial, sans-serif;
      font-size: 9pt;
      color: #666;
      margin-bottom: 0.8cm;
    }

    /* Headings */
    h1, h2, h3, h4, h5, h6 {
      font-family: 'Helvetica Neue', Arial, sans-serif;
      font-weight: 700;
      margin-top: 0.7cm;
      margin-bottom: 0.2cm;
      color: #111;
      page-break-after: avoid;
    }
    h1 { font-size: 17pt; border-bottom: 1px solid #ddd; padding-bottom: 0.15cm; }
    h2 { font-size: 14pt; }
    h3 { font-size: 12pt; }

    /* Body text */
    p { margin: 0.25cm 0; orphans: 3; widows: 3; }
    strong { font-weight: 700; }
    em { font-style: italic; }

    /* Lists */
    ul, ol { margin: 0.25cm 0 0.25cm 0.7cm; }
    li { margin: 0.1cm 0; }
    li > ul, li > ol { margin-top: 0.05cm; }

    /* Code */
    code {
      font-family: 'Courier New', Courier, monospace;
      font-size: 10pt;
      background: #f5f5f5;
      padding: 1px 4px;
      border-radius: 3px;
    }
    pre {
      background: #f5f5f5;
      border: 1px solid #e0e0e0;
      border-radius: 4px;
      padding: 0.3cm;
      margin: 0.3cm 0;
      overflow: auto;
      font-size: 9.5pt;
      page-break-inside: avoid;
    }
    pre code { background: none; padding: 0; }

    /* Blockquote */
    blockquote {
      border-left: 3px solid #999;
      margin: 0.3cm 0 0.3cm 0.4cm;
      padding-left: 0.3cm;
      color: #555;
      font-style: italic;
    }

    /* Tables */
    table {
      width: 100%;
      border-collapse: collapse;
      margin: 0.3cm 0;
      font-size: 10.5pt;
      page-break-inside: avoid;
    }
    th {
      background: #f0f0f0;
      font-weight: 700;
      text-align: left;
      padding: 0.15cm 0.25cm;
      border: 1px solid #ccc;
    }
    td {
      padding: 0.12cm 0.25cm;
      border: 1px solid #ddd;
    }
    tr:nth-child(even) td { background: #fafafa; }

    /* Horizontal rule */
    hr { border: none; border-top: 1px solid #ddd; margin: 0.5cm 0; }

    /* Links */
    a { color: #1a56db; text-decoration: underline; }

    /* Print optimisations */
    @media print {
      body { padding: 0; }
      .doc-title { font-size: 20pt; }
      a { color: #000; }
      @page { margin: 2cm 2.5cm; }
    }
  </style>
</head>
<body>
  <div class="doc-title">${escapeHTML(title)}</div>
  <div class="doc-meta">Generated by SCX.ai · ${new Date().toLocaleDateString('en-AU', { day: 'numeric', month: 'long', year: 'numeric' })}</div>
  <div id="content"></div>
  <script>
    // Use marked (loaded inline) to parse markdown at runtime in the print window
    const md = ${JSON.stringify(content)};

    // Simple but robust markdown → HTML conversion using a tiny subset parser
    // We rely on the browser's innerHTML for rendering, which is safe here since
    // we control the content (it came from our AI model).
    function mdToHTML(text) {
      return text
        // Fenced code blocks
        .replace(/\`\`\`[\\w]*\\n?([\\s\\S]*?)\`\`\`/g, '<pre><code>$1</code></pre>')
        // Headings
        .replace(/^###### (.+)$/gm, '<h6>$1</h6>')
        .replace(/^##### (.+)$/gm, '<h5>$1</h5>')
        .replace(/^#### (.+)$/gm, '<h4>$1</h4>')
        .replace(/^### (.+)$/gm, '<h3>$1</h3>')
        .replace(/^## (.+)$/gm, '<h2>$1</h2>')
        .replace(/^# (.+)$/gm, '<h1>$1</h1>')
        // HR
        .replace(/^---+$/gm, '<hr/>')
        // Blockquote
        .replace(/^> (.+)$/gm, '<blockquote>$1</blockquote>')
        // Unordered lists (basic)
        .replace(/^[\\*\\-] (.+)$/gm, '<li>$1</li>')
        .replace(/(<li>.*<\\/li>\\n?)+/g, '<ul>$&</ul>')
        // Ordered lists (basic)
        .replace(/^\\d+\\. (.+)$/gm, '<li>$1</li>')
        // Bold
        .replace(/\\*\\*(.+?)\\*\\*/g, '<strong>$1</strong>')
        .replace(/__(.+?)__/g, '<strong>$1</strong>')
        // Italic
        .replace(/\\*(.+?)\\*/g, '<em>$1</em>')
        .replace(/_(.+?)_/g, '<em>$1</em>')
        // Inline code
        .replace(/\`(.+?)\`/g, '<code>$1</code>')
        // Links
        .replace(/\\[([^\\]]+)\\]\\(([^)]+)\\)/g, '<a href="$2">$1</a>')
        // Paragraphs (double newline)
        .replace(/\\n\\n([^<])/g, '\\n<p>$1')
        // Line breaks
        .replace(/\\n/g, '<br/>');
    }

    document.getElementById('content').innerHTML = mdToHTML(md);
    window.onload = function() { window.print(); };
  </script>
</body>
</html>`;

  printWindow.document.write(html);
  printWindow.document.close();
}

function escapeHTML(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

const DOC_TYPE_LABELS: Record<string, string> = {
  report: 'Report',
  essay: 'Essay',
  article: 'Article',
  guide: 'Guide',
  summary: 'Summary',
  analysis: 'Analysis',
  other: 'Document',
};

export function DocumentCard({
  title,
  description,
  content,
  documentType = 'report',
  wordCount,
  generatedAt,
}: DocumentCardProps) {
  const [copied, setCopied] = useState(false);
  const [expanded, setExpanded] = useState(true);

  const handleCopy = useCallback(async () => {
    await navigator.clipboard.writeText(content);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }, [content]);

  const handleDownload = useCallback(() => {
    printAsPDF(title, content);
  }, [title, content]);

  const typeLabel = DOC_TYPE_LABELS[documentType] ?? 'Document';
  const date = generatedAt
    ? new Date(generatedAt).toLocaleDateString('en-AU', {
        day: 'numeric',
        month: 'short',
        year: 'numeric',
      })
    : null;

  return (
    <div className="my-4 overflow-hidden rounded-2xl border border-zinc-200 bg-white shadow-sm dark:border-zinc-700 dark:bg-zinc-900">
      {/* Header */}
      <div className="flex items-start gap-3 border-b border-zinc-100 bg-zinc-50 px-5 py-4 dark:border-zinc-700/60 dark:bg-zinc-800/60">
        <div className="mt-0.5 flex h-9 w-9 shrink-0 items-center justify-center rounded-lg bg-blue-600/10">
          <FileText className="h-4 w-4 text-blue-600 dark:text-blue-400" />
        </div>
        <div className="min-w-0 flex-1">
          <div className="flex items-center gap-2">
            <span className="rounded-full bg-blue-100 px-2 py-0.5 text-xs font-medium text-blue-700 dark:bg-blue-900/40 dark:text-blue-300">
              {typeLabel}
            </span>
            {wordCount && (
              <span className="text-xs text-zinc-400">{wordCount.toLocaleString()} words</span>
            )}
            {date && <span className="text-xs text-zinc-400">{date}</span>}
          </div>
          <h3 className="mt-0.5 text-base font-semibold text-zinc-900 dark:text-white leading-tight">
            {title}
          </h3>
          {description && (
            <p className="mt-0.5 text-sm text-zinc-500 dark:text-zinc-400 leading-snug">
              {description}
            </p>
          )}
        </div>
        <button
          onClick={() => setExpanded((v) => !v)}
          className="shrink-0 rounded-lg p-1.5 text-zinc-400 transition hover:bg-zinc-100 hover:text-zinc-600 dark:hover:bg-zinc-700 dark:hover:text-zinc-300"
          aria-label={expanded ? 'Collapse document' : 'Expand document'}
        >
          {expanded ? <ChevronUp className="h-4 w-4" /> : <ChevronDown className="h-4 w-4" />}
        </button>
      </div>

      {/* Document body */}
      {expanded && (
        <div className="max-h-[60vh] overflow-y-auto px-6 py-5">
          <div className="prose prose-zinc dark:prose-invert max-w-none prose-headings:font-semibold prose-h1:text-xl prose-h2:text-lg prose-h3:text-base prose-p:leading-relaxed prose-li:leading-relaxed prose-code:text-sm prose-code:bg-zinc-100 prose-code:dark:bg-zinc-800 prose-code:px-1 prose-code:py-0.5 prose-code:rounded prose-pre:bg-zinc-100 prose-pre:dark:bg-zinc-800 prose-blockquote:border-l-blue-400 prose-blockquote:text-zinc-500 prose-table:text-sm">
            <ReactMarkdown remarkPlugins={[remarkGfm]}>{content}</ReactMarkdown>
          </div>
        </div>
      )}

      {/* Actions */}
      <div className="flex flex-wrap items-center gap-2 border-t border-zinc-100 bg-zinc-50 px-5 py-3 dark:border-zinc-700/60 dark:bg-zinc-800/40">
        <button
          onClick={handleDownload}
          className="inline-flex items-center gap-1.5 rounded-lg bg-blue-600 px-3 py-1.5 text-sm font-medium text-white shadow-sm transition hover:bg-blue-500 active:scale-95"
        >
          <Download className="h-3.5 w-3.5" />
          Download PDF
        </button>
        <button
          onClick={handleCopy}
          className="inline-flex items-center gap-1.5 rounded-lg border border-zinc-200 bg-white px-3 py-1.5 text-sm font-medium text-zinc-700 shadow-sm transition hover:bg-zinc-50 active:scale-95 dark:border-zinc-600 dark:bg-zinc-800 dark:text-zinc-300 dark:hover:bg-zinc-700"
        >
          {copied ? (
            <>
              <Check className="h-3.5 w-3.5 text-emerald-500" />
              Copied!
            </>
          ) : (
            <>
              <Copy className="h-3.5 w-3.5" />
              Copy Markdown
            </>
          )}
        </button>
        <a
          href="https://markdowntopdf.com"
          target="_blank"
          rel="noopener noreferrer"
          className="inline-flex items-center gap-1 text-xs text-zinc-400 transition hover:text-zinc-600 dark:hover:text-zinc-300"
        >
          <ExternalLink className="h-3 w-3" />
          or paste into markdowntopdf.com
        </a>
      </div>
    </div>
  );
}
