import { wrapLanguageModel, customProvider, extractReasoningMiddleware } from 'ai';

import { openai } from '@ai-sdk/openai';
import { xai } from '@ai-sdk/xai';
import { groq } from '@ai-sdk/groq';
import { anthropic } from '@ai-sdk/anthropic';
import { google } from '@ai-sdk/google';
import { mistral } from '@ai-sdk/mistral';

const middleware = extractReasoningMiddleware({
  tagName: 'think',
});

export const scira = customProvider({
  languageModels: {
    'scira-default': xai('grok-3-mini'),
    'scira-fast': xai('grok-3-mini-fast-latest'),
    'scira-grok-3': xai('grok-3'),
    'scira-vision': xai('grok-2-vision-1212'),
    'scira-g2': xai('grok-2-latest'),
    'scira-4o-mini': openai.responses('gpt-4o-mini'),
    'scira-o4-mini': openai.responses('o4-mini-2025-04-16'),
    'scira-o3': openai.responses('o3'),
    'scira-qwq': wrapLanguageModel({
      model: groq('qwen-qwq-32b', {
        parallelToolCalls: false,
      }),
      middleware,
    }),
    'scira-qwen-32b': wrapLanguageModel({
      model: groq('qwen/qwen3-32b', {
        parallelToolCalls: false,
      }),
      middleware,
    }),
    'scira-haiku': anthropic('claude-3-5-haiku-20241022'),
    'scira-mistral': mistral('mistral-small-latest'),
    'scira-google-lite': google('gemini-2.5-flash-lite-preview-06-17'),
    'scira-google': google('gemini-2.5-flash'),
    'scira-google-pro': google('gemini-2.5-pro'),
    'scira-anthropic': anthropic('claude-sonnet-4-20250514'),
    'scira-anthropic-thinking': anthropic('claude-sonnet-4-20250514'),
    'scira-opus': anthropic('claude-4-opus-20250514'),
    'scira-opus-pro': anthropic('claude-4-opus-20250514'),
    'scira-llama-4': groq('meta-llama/llama-4-maverick-17b-128e-instruct', {
      parallelToolCalls: false,
    }),
  },
});


export const models = [
  {
    value: 'scira-default',
    label: 'Grok 3.0 Mini',
    description: "xAI's most efficient reasoning model",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Mini',
    pdf: false,
    pro: false,
  },
  {
    value: 'scira-grok-3',
    label: 'Grok 3.0',
    description: "xAI's most intelligent model",
    vision: false,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: false,
    pro: true,
  },
  {
    value: 'scira-vision',
    label: 'Grok 2.0 Vision',
    description: "xAI's advanced vision model",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Mini',
    pdf: false,
    pro: false,
  },
  {
    value: 'scira-mistral',
    label: 'Mistral Small',
    description: "Mistral's small model",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Mini',
    pdf: true,
    pro: false,
  },
  {
    value: 'scira-anthropic',
    label: 'Claude 4 Sonnet',
    description: "Anthropic's most advanced model",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
  },
  {
    value: 'scira-anthropic-thinking',
    label: 'Claude 4 Sonnet Thinking',
    description: "Anthropic's most advanced reasoning model",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
  },
  {
    value: 'scira-opus',
    label: 'Claude 4 Opus',
    description: "Anthropic's most advanced reasoning model",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
  },
  {
    value: 'scira-opus-pro',
    label: 'Claude 4 Opus Thinking',
    description: "Anthropic's most advanced reasoning model",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
  },
  {
    value: 'scira-google-lite',
    label: 'Gemini 2.5 Flash Lite',
    description: "Google's advanced small reasoning model",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Mini',
    pdf: true,
    pro: false,
  },
  {
    value: 'scira-google',
    label: 'Gemini 2.5 Flash',
    description: "Google's advanced small reasoning model",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
  },
  {
    value: 'scira-google-pro',
    label: 'Gemini 2.5 Pro',
    description: "Google's advanced reasoning model",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
  },
  {
    value: 'scira-4o-mini',
    label: 'GPT 4o Mini',
    description: "OpenAI's flagship model",
    vision: true,
    reasoning: false,
    experimental: false,
    category: 'Mini',
    pdf: true,
    pro: false,
  },
  {
    value: 'scira-o4-mini',
    label: 'o4 mini',
    description: "OpenAI's faster mini reasoning model",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
  },
  {
    value: 'scira-o3',
    label: 'o3',
    description: "OpenAI's big reasoning model",
    vision: true,
    reasoning: true,
    experimental: false,
    category: 'Pro',
    pdf: true,
    pro: true,
  },
  {
    value: 'scira-llama-4',
    label: 'Llama 4 Maverick',
    description: "Meta's latest model",
    vision: true,
    reasoning: false,
    experimental: true,
    category: 'Experimental',
    pdf: false,
    pro: false,
  },
  {
    value: 'scira-qwen-32b',
    label: 'Qwen 3 32B',
    description: "Alibaba's advanced reasoning model",
    vision: false,
    reasoning: true,
    experimental: false,
    category: 'Mini',
    pdf: false,
    pro: false,
  },
  {
    value: 'scira-qwq',
    label: 'QWQ 32B',
    description: "Alibaba's advanced reasoning model",
    vision: false,
    reasoning: true,
    experimental: true,
    category: 'Experimental',
    pdf: false,
    pro: false,
  },
];
